"use client";
import { useState } from "react";
import { CornerDownRight } from "lucide-react";
import type { Comment } from "@/lib/types";
import { Avatar } from "@/components/avatar";
import { formatDate } from "@/lib/utils";
import { CommentForm } from "@/components/comment-form";
export function Comments({ comments, articleId, slug, signedIn }: { comments: Comment[]; articleId: string; slug: string; signedIn: boolean }) {
  const byParent = new Map<string | null, Comment[]>(); comments.forEach(c => byParent.set(c.parent_id, [...(byParent.get(c.parent_id) ?? []), c]));
  return <section className="mt-16"><h2 className="font-serif text-2xl text-paper">Tartışma <span className="text-zinc-500">({comments.length})</span></h2>{signedIn ? <CommentForm articleId={articleId} slug={slug} /> : <p className="mt-5 rounded-lg border border-white/10 bg-white/[.03] p-4 text-sm text-zinc-400">Tartışmaya katılmak için giriş yapmalısın.</p>}<div className="mt-8 space-y-5">{(byParent.get(null) ?? []).map(comment => <CommentNode key={comment.id} comment={comment} depth={0} children={byParent} articleId={articleId} slug={slug} signedIn={signedIn} />)}</div></section>;
}
function CommentNode({ comment, depth, children, articleId, slug, signedIn }: { comment: Comment; depth: number; children: Map<string | null, Comment[]>; articleId: string; slug: string; signedIn: boolean }) { const [reply, setReply] = useState(false); const replies = children.get(comment.id) ?? []; return <article className={depth ? "ml-3 border-l border-white/10 pl-4 sm:ml-6" : ""}><div className="flex gap-3"><Avatar path={comment.profiles?.avatar_path} name={comment.profiles?.display_name ?? "Üye"} size="sm" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2"><span className="text-sm font-semibold text-paper">{comment.profiles?.display_name ?? "Üye"}</span>{comment.profiles?.title && <span className="rounded bg-amber/10 px-1.5 py-0.5 text-[10px] font-semibold text-amber">{comment.profiles.title}</span>}<time className="text-xs text-zinc-600">{formatDate(comment.created_at)}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-zinc-300">{comment.body}</p>{signedIn && <button onClick={() => setReply(!reply)} className="mt-2 inline-flex items-center gap-1 text-xs font-medium text-zinc-500 hover:text-amber"><CornerDownRight size={14} /> Yanıtla</button>}{reply && <CommentForm articleId={articleId} slug={slug} parentId={comment.id} compact />}</div></div>{replies.length > 0 && <div className="mt-5 space-y-5">{replies.map(child => <CommentNode key={child.id} comment={child} depth={depth + 1} children={children} articleId={articleId} slug={slug} signedIn={signedIn} />)}</div>}</article>; }
